# Generated by Django 2.1 on 2018-10-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181021_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='status',
            field=models.CharField(choices=[('tbd', 'TBD'), ('ready', 'Ready'), ('in_flight', 'In Flight'), ('success', 'Success'), ('hold', 'Hold'), ('failure', 'Failure'), ('partial_failure', 'Partial Failure')], default='tbd', max_length=255, verbose_name='Status'),
        ),
    ]
